#!/usr/bin/env python3
"""
figures/fixtures/make_mock_fixtures.py

Generates synthetic JSON matching the schema figures/common.py expects, so
every script in figures/ can be run and reviewed before real results exist.
Every file this writes is stamped "_mock": true and every number in it is
synthetic — none of it should ever be pasted into the manuscript.

Run:  python figures/fixtures/make_mock_fixtures.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

FIXTURES_DIR = Path(__file__).resolve().parent
CLASS_NAMES = ["glioma", "meningioma", "pituitary", "notumor"]
SEEDS = [42, 123, 7, 2024, 31]
N_PER_SEED = 60  # ~ toy test-set size per seed, not the real split size

RNG = np.random.default_rng(20260620)


def _synthetic_predictions(model: str, seed: int, base_acc: float, base_ece: float) -> dict:
    """A mock MC-Dropout prediction dump for one (model, seed).

    Built to look like a plausible-but-mediocre real classifier: correct
    predictions get higher confidence and lower entropy on average, wrong
    ones lower confidence and higher entropy, with per-model/per-seed noise.
    """
    rng = np.random.default_rng(hash((model, seed)) % (2**32))
    n = N_PER_SEED
    y_true = rng.integers(0, 4, size=n)

    mean_probs = np.zeros((n, 4))
    y_pred = np.zeros(n, dtype=int)
    for i, label in enumerate(y_true):
        correct = rng.random() < base_acc
        if correct:
            conf = np.clip(rng.normal(1 - base_ece, 0.12), 0.28, 0.98)
            probs = rng.dirichlet(np.ones(4) * 0.6)
            probs = probs * (1 - conf)
            probs[label] = conf
            probs /= probs.sum()
            pred = label
        else:
            probs = rng.dirichlet(np.ones(4) * 1.5)
            wrong_choices = [c for c in range(4) if c != label]
            pred = int(rng.choice(wrong_choices))
            if probs.argmax() == label:
                probs[[pred, label]] = probs[[label, pred]]
        mean_probs[i] = probs
        y_pred[i] = pred

    entropy = -(mean_probs * np.log2(mean_probs + 1e-10)).sum(axis=1)

    return {
        "_mock": True,
        "model": model,
        "seed": seed,
        "class_names": CLASS_NAMES,
        "provenance": {
            "is_smoke_test_run": False,
            "caveat": "MOCK fixture data generated by figures/fixtures/make_mock_fixtures.py "
                      "for figure-script testing. Not from any real training or evaluation run.",
        },
        "y_true": y_true.tolist(),
        "y_pred": y_pred.tolist(),
        "mean_probs": mean_probs.tolist(),
        "entropy": entropy.tolist(),
    }


def _aggregate_from_predictions(model: str, seed: int, pred: dict) -> dict:
    y_true = np.array(pred["y_true"])
    y_pred = np.array(pred["y_pred"])
    mean_probs = np.array(pred["mean_probs"])
    entropy = np.array(pred["entropy"])

    acc = float((y_pred == y_true).mean())
    correct = (y_pred == y_true).astype(float)
    order = np.argsort(entropy)
    correct_s = correct[order]
    n = len(y_true)
    coverage = np.arange(1, n + 1) / n
    risk = 1.0 - np.cumsum(correct_s) / np.arange(1, n + 1)
    aurc = float(np.trapezoid(risk, coverage) if hasattr(np, "trapezoid") else np.trapz(risk, coverage))

    confidence = mean_probs.max(axis=1)
    ece = 0.0
    for lo, hi in zip(np.linspace(0, 1, 16)[:-1], np.linspace(0, 1, 16)[1:]):
        m = (confidence > lo) & (confidence <= hi)
        if m.sum() == 0:
            continue
        ece += abs(correct[m].mean() - confidence[m].mean()) * m.sum() / n

    one_hot = np.eye(4)[y_true]
    brier = float(np.mean(np.sum((mean_probs - one_hot) ** 2, axis=1)))

    acc_at = {}
    for level in (0.80, 0.90, 0.95):
        k = max(1, int(n * level))
        acc_at[level] = float(correct_s[:k].mean())

    lo_ci, hi_ci = max(0.0, acc - 0.15), min(1.0, acc + 0.15)

    return {
        "model": model, "seed": seed,
        "best_val_loss": round(float(RNG.uniform(0.6, 1.1)), 4),
        "best_val_acc": round(acc + float(RNG.uniform(-0.05, 0.05)), 4),
        "test_loss": round(float(RNG.uniform(0.6, 1.3)), 4),
        "test_acc": round(acc, 4),
        "mc_acc": round(acc, 4),
        "macro_f1": round(max(0.0, acc - 0.03), 4),
        "macro_auc": round(min(0.999, acc + 0.18), 4),
        "mean_entropy": round(float(entropy.mean()), 4),
        "ece": round(ece, 4),
        "brier": round(brier, 4),
        "aurc": round(aurc, 4),
        "acc_at_80": round(acc_at[0.80], 4),
        "acc_at_90": round(acc_at[0.90], 4),
        "acc_at_95": round(acc_at[0.95], 4),
        "acc_ci_lo": round(lo_ci, 4),
        "acc_ci_hi": round(hi_ci, 4),
        "auc_ci_lo": round(max(0.0, acc + 0.18 - 0.12), 4),
        "auc_ci_hi": round(min(1.0, acc + 0.18 + 0.12), 4),
        "ood_auroc": round(float(RNG.uniform(0.6, 0.85)), 4),
    }


def main() -> None:
    analysis_dir = FIXTURES_DIR / "analysis_results"
    analysis_dir.mkdir(parents=True, exist_ok=True)

    # ViT set to be modestly better-calibrated / more accurate than ResNet-50,
    # consistent with src/code.py's docstring framing (MC-Dropout T=20, both models
    # selectively fine-tuned) — purely illustrative, not a claim about real results.
    model_params = {
        "vit": {"base_acc": 0.66, "base_ece": 0.10},
        "resnet50": {"base_acc": 0.58, "base_ece": 0.16},
    }

    per_model_aggregates = {m: {k: [] for k in [
        "model", "seed", "best_val_loss", "best_val_acc", "test_loss", "test_acc",
        "mc_acc", "macro_f1", "macro_auc", "mean_entropy", "ece", "brier", "aurc",
        "acc_at_80", "acc_at_90", "acc_at_95", "acc_ci_lo", "acc_ci_hi",
        "auc_ci_lo", "auc_ci_hi", "ood_auroc",
    ]} for m in model_params}

    mcnemar_per_seed = []

    for seed in SEEDS:
        preds_by_model = {}
        for model, params in model_params.items():
            pred = _synthetic_predictions(model, seed, **params)
            preds_by_model[model] = pred
            out_path = analysis_dir / f"{model}_seed{seed}_predictions.json"
            with open(out_path, "w") as f:
                json.dump(pred, f, indent=2)

            agg = _aggregate_from_predictions(model, seed, pred)
            for k, v in agg.items():
                per_model_aggregates[model][k].append(v)

        vit_acc = per_model_aggregates["vit"]["test_acc"][-1]
        rn_acc = per_model_aggregates["resnet50"]["test_acc"][-1]
        y_true_v = np.array(preds_by_model["vit"]["y_true"])
        y_pred_v = np.array(preds_by_model["vit"]["y_pred"])
        y_pred_r = np.array(preds_by_model["resnet50"]["y_pred"])
        n = min(len(y_true_v), len(y_pred_r))
        correct_v = (y_pred_v[:n] == y_true_v[:n])
        correct_r = (y_pred_r[:n] == y_true_v[:n])
        b = int((correct_v & ~correct_r).sum())
        c = int((~correct_v & correct_r).sum())
        if b + c == 0:
            chi2, pval = 0.0, 1.0
        else:
            chi2 = float((abs(b - c) - 1) ** 2 / (b + c))
            from scipy.stats import chi2 as scipy_chi2
            pval = float(1.0 - scipy_chi2.cdf(chi2, df=1))
        mcnemar_per_seed.append({
            "seed": seed, "chi2": round(chi2, 4), "p_value": round(pval, 6),
            "significant": bool(pval < 0.05),
            "direction": "vit_better" if vit_acc > rn_acc else "resnet50_better",
            "vit_acc": round(vit_acc, 4), "rn_acc": round(rn_acc, 4),
        })

    master_summary = {
        "_mock": True,
        "_note": "Synthetic fixture for figure-script testing. Generated by "
                 "figures/fixtures/make_mock_fixtures.py. Do not cite any number "
                 "in this file in the manuscript.",
        "class_names": CLASS_NAMES,
        "seeds": SEEDS,
        "vit": per_model_aggregates["vit"],
        "resnet50": per_model_aggregates["resnet50"],
        "mcnemar_per_seed": mcnemar_per_seed,
    }
    with open(FIXTURES_DIR / "master_summary.json", "w") as f:
        json.dump(master_summary, f, indent=2)

    print(f"Wrote {FIXTURES_DIR / 'master_summary.json'}")
    print(f"Wrote {len(SEEDS) * len(model_params)} prediction files under {analysis_dir}")


if __name__ == "__main__":
    main()
