"""
src/legacy_figures.py

SUPERSEDED — kept for reference only. The manuscript's actual figures are
generated by the real pipeline in figures/ (figures/calibration_reliability.py,
figures/confusion_matrix.py, etc., writing to figures/output/), which consumes
real results/master_summary.json and analysis/results/*_predictions.json.
This script predates that pipeline, only ever ran on synthetic/dummy data,
and is not wired to any real data source. Do not cite its output as a
manuscript figure.

Publication-Ready Figure Suite (legacy)
Brain Tumor Classification — ViT + MC Dropout Uncertainty Quantification
Target: Nature Scientific Reports / IEEE TMI

Figures generated (each saved as PDF + PNG @ 300 DPI):
  fig1  — Training Dynamics (Loss + Accuracy)
  fig2  — Enhanced Confusion Matrix
  fig3  — Multi-Class ROC & Precision–Recall Curves
  fig4  — Uncertainty Reliability (Violin + Scatter)
  fig5  — Model Calibration (Reliability Diagram)
  fig6  — Accuracy–Rejection Curve (Clinical Deferral)
  fig7  — t-SNE Latent Space Projection (Class + Uncertainty)

Usage:
  python src/legacy_figures.py         # runs on synthetic data → ./legacy_figures_output/
  from legacy_figures import *         # import into your training notebook
"""

import os
import warnings
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.lines import Line2D
from sklearn.metrics import (
    confusion_matrix,
    roc_curve, auc,
    precision_recall_curve, average_precision_score,
)
from sklearn.preprocessing import label_binarize
from sklearn.manifold import TSNE
from sklearn.calibration import calibration_curve

warnings.filterwarnings("ignore")

# ── Constants ──────────────────────────────────────────────────────────────────
CLASS_NAMES = ["Glioma", "Meningioma", "Pituitary", "No Tumor"]
N_CLASSES   = 4
OUTPUT_DIR  = "legacy_figures_output"

# Wong (2011) color-blind-safe palette — maps 1:1 to CLASS_NAMES
_CB4 = ["#0072B2", "#E69F00", "#009E73", "#CC79A7"]
# Red for misclassified; kept separate so it never collides with class colors
_RED = "#D62728"


# ══════════════════════════════════════════════════════════════════════════════
# Global Style
# ══════════════════════════════════════════════════════════════════════════════

def set_global_style() -> None:
    """Apply Nature-journal matplotlib rcParams globally."""
    # Prefer Arial; fall back gracefully on systems where it is absent.
    _font = "Arial" if "Arial" in matplotlib.font_manager.get_font_names() else "DejaVu Sans"
    matplotlib.rcParams.update({
        # Font
        "font.family":        _font,
        "font.size":          10,
        "axes.labelsize":     12,
        "axes.titlesize":     14,
        "axes.titleweight":   "bold",
        "axes.titlepad":      8,
        # Ticks
        "xtick.labelsize":    10,
        "ytick.labelsize":    10,
        "xtick.direction":    "out",
        "ytick.direction":    "out",
        "xtick.major.size":   3.5,
        "ytick.major.size":   3.5,
        # Spines (Tufte style — top/right removed per axis via _despine)
        "axes.spines.top":    False,
        "axes.spines.right":  False,
        "axes.linewidth":     0.8,
        # Legend
        "legend.fontsize":    9,
        "legend.frameon":     False,
        "legend.handlelength": 1.5,
        # Lines
        "lines.linewidth":    1.8,
        # Resolution
        "figure.dpi":         120,   # screen preview
        "savefig.dpi":        300,   # export
        # PDF text as editable paths (not bitmap/Type3)
        "pdf.fonttype":       42,
        "ps.fonttype":        42,
    })


def _despine(ax: plt.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


# ══════════════════════════════════════════════════════════════════════════════
# Save Helper
# ══════════════════════════════════════════════════════════════════════════════

def save_figure(fig: plt.Figure, stem: str) -> None:
    """Export *fig* as both PDF and PNG at 300 DPI into OUTPUT_DIR."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    for fmt in ("pdf", "png"):
        path = os.path.join(OUTPUT_DIR, f"{stem}.{fmt}")
        fig.savefig(path, dpi=300, bbox_inches="tight", format=fmt)
        print(f"    Saved → {path}")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 1 — Training Dynamics
# ══════════════════════════════════════════════════════════════════════════════

def plot_training_dynamics(history: dict, best_epoch: int | None = None) -> plt.Figure:
    """
    1×2 grid: Cross-Entropy Loss (left) and Accuracy (right).
    A vertical dotted line marks the epoch at which the best model was saved.

    Parameters
    ----------
    history     : dict with keys train_loss, val_loss, train_acc, val_acc
    best_epoch  : 1-indexed epoch of the best checkpoint (auto-detected from
                  minimum val_loss if None)
    """
    n_epochs = len(history["train_loss"])
    epochs   = np.arange(1, n_epochs + 1)

    if best_epoch is None:
        best_epoch = int(np.argmin(history["val_loss"])) + 1

    fig, axes = plt.subplots(1, 2, figsize=(10, 4), constrained_layout=True)

    # ── Loss ──────────────────────────────────────────────────────────────────
    ax = axes[0]
    ax.plot(epochs, history["train_loss"], color=_CB4[0], label="Train")
    ax.plot(epochs, history["val_loss"],   color=_CB4[1], linestyle="--", label="Validation")
    ax.axvline(best_epoch, color="gray", linestyle=":", linewidth=1.2,
               label=f"Best checkpoint (ep. {best_epoch})")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Cross-Entropy Loss")
    ax.set_title("Training & Validation Loss")
    ax.legend()
    _despine(ax)

    # ── Accuracy ──────────────────────────────────────────────────────────────
    ax = axes[1]
    ax.plot(epochs, history["train_acc"], color=_CB4[0], label="Train")
    ax.plot(epochs, history["val_acc"],   color=_CB4[1], linestyle="--", label="Validation")
    ax.axvline(best_epoch, color="gray", linestyle=":", linewidth=1.2,
               label=f"Best checkpoint (ep. {best_epoch})")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Accuracy")
    ax.set_ylim(0, 1.05)
    ax.set_title("Training & Validation Accuracy")
    ax.legend()
    _despine(ax)

    save_figure(fig, "fig1_training_dynamics")
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# Figure 2 — Enhanced Confusion Matrix
# ══════════════════════════════════════════════════════════════════════════════

def plot_confusion_matrix(y_true: np.ndarray, y_pred: np.ndarray) -> plt.Figure:
    """
    Confusion matrix annotated with raw counts AND row-normalized percentage.
    Single-hue Blues gradient; text color adapts to cell brightness.

    Parameters
    ----------
    y_true  : (N,) integer class indices
    y_pred  : (N,) integer class indices
    """
    cm      = confusion_matrix(y_true, y_pred)
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

    fig, ax = plt.subplots(figsize=(6.5, 5.5))
    im = ax.imshow(cm_norm, cmap="Blues", vmin=0, vmax=1, aspect="auto")

    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label("Proportion of True Class", fontsize=10)
    cbar.ax.tick_params(labelsize=8)

    # Annotate each cell
    threshold = 0.55   # switch text to white above this normalized value
    for r in range(N_CLASSES):
        for c in range(N_CLASSES):
            val    = cm_norm[r, c]
            color  = "white" if val > threshold else "black"
            weight = "bold"  if r == c else "normal"
            ax.text(c, r,
                    f"{cm[r, c]}\n({val*100:.1f}%)",
                    ha="center", va="center",
                    fontsize=9, color=color, fontweight=weight)

    ax.set_xticks(range(N_CLASSES))
    ax.set_yticks(range(N_CLASSES))
    ax.set_xticklabels(CLASS_NAMES, rotation=35, ha="right", fontsize=10)
    ax.set_yticklabels(CLASS_NAMES, fontsize=10)
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")
    ax.set_title("Confusion Matrix")
    # Keep all four spines for a matrix boundary
    for spine in ax.spines.values():
        spine.set_visible(True)

    fig.tight_layout()
    save_figure(fig, "fig2_confusion_matrix")
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# Figure 3 — Multi-Class ROC & Precision–Recall Curves
# ══════════════════════════════════════════════════════════════════════════════

def plot_roc_pr_curves(y_true: np.ndarray, y_probs: np.ndarray) -> plt.Figure:
    """
    1×2 grid.
    Left : ROC curves for all 4 classes + macro + micro averages.
    Right: Precision–Recall curves for all 4 classes + micro average.
    AUC / AP values appear in legend labels (3 decimal places).

    Parameters
    ----------
    y_true  : (N,) integer class indices
    y_probs : (N, 4) predicted probability array
    """
    y_bin = label_binarize(y_true, classes=list(range(N_CLASSES)))
    fig, axes = plt.subplots(1, 2, figsize=(12, 5), constrained_layout=True)

    # ── ROC ───────────────────────────────────────────────────────────────────
    ax = axes[0]
    fpr_store, tpr_store = {}, {}
    for i, name in enumerate(CLASS_NAMES):
        fpr, tpr, _ = roc_curve(y_bin[:, i], y_probs[:, i])
        roc_auc = auc(fpr, tpr)
        fpr_store[i], tpr_store[i] = fpr, tpr
        ax.plot(fpr, tpr, color=_CB4[i], linewidth=1.8,
                label=f"{name}  (AUC = {roc_auc:.3f})")

    # Micro-average
    fpr_m, tpr_m, _ = roc_curve(y_bin.ravel(), y_probs.ravel())
    ax.plot(fpr_m, tpr_m, "k--", linewidth=1.4,
            label=f"Micro-avg  (AUC = {auc(fpr_m, tpr_m):.3f})")

    # Macro-average (interpolated)
    all_fpr   = np.unique(np.concatenate([fpr_store[i] for i in range(N_CLASSES)]))
    mean_tpr  = sum(np.interp(all_fpr, fpr_store[i], tpr_store[i])
                    for i in range(N_CLASSES)) / N_CLASSES
    ax.plot(all_fpr, mean_tpr, "k:", linewidth=1.4,
            label=f"Macro-avg  (AUC = {auc(all_fpr, mean_tpr):.3f})")

    ax.plot([0, 1], [0, 1], color="silver", linewidth=1.0)  # chance line
    ax.set_xlim(-0.01, 1.01)
    ax.set_ylim(-0.01, 1.05)
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate (Sensitivity)")
    ax.set_title("Receiver Operating Characteristic")
    ax.legend(loc="lower right", fontsize=8.5)
    _despine(ax)

    # ── Precision–Recall ──────────────────────────────────────────────────────
    ax = axes[1]
    for i, name in enumerate(CLASS_NAMES):
        prec, rec, _ = precision_recall_curve(y_bin[:, i], y_probs[:, i])
        ap = average_precision_score(y_bin[:, i], y_probs[:, i])
        ax.plot(rec, prec, color=_CB4[i], linewidth=1.8,
                label=f"{name}  (AP = {ap:.3f})")

    # Micro-average PR
    ap_micro  = average_precision_score(y_bin, y_probs, average="micro")
    prec_mi, rec_mi, _ = precision_recall_curve(y_bin.ravel(), y_probs.ravel())
    ax.plot(rec_mi, prec_mi, "k--", linewidth=1.4,
            label=f"Micro-avg  (AP = {ap_micro:.3f})")

    ax.set_xlim(-0.01, 1.01)
    ax.set_ylim(-0.01, 1.05)
    ax.set_xlabel("Recall")
    ax.set_ylabel("Precision")
    ax.set_title("Precision–Recall Curves")
    ax.legend(loc="upper right", fontsize=8.5)
    _despine(ax)

    save_figure(fig, "fig3_roc_pr_curves")
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# Figure 4 — Uncertainty Reliability (Violin + Scatter)
# ══════════════════════════════════════════════════════════════════════════════

def plot_uncertainty_reliability(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    y_probs: np.ndarray,
    uncertainties: np.ndarray,
) -> plt.Figure:
    """
    1×2 grid.
    Left : Violin plot — predictive entropy for Correct vs. Misclassified.
    Right: Scatter — max confidence vs. entropy, colored by correctness.

    Parameters
    ----------
    y_true        : (N,) true class indices
    y_pred        : (N,) predicted class indices
    y_probs       : (N, 4) predicted probabilities
    uncertainties : (N,) predictive entropy values (bits)
    """
    correct  = y_true == y_pred
    max_conf = y_probs.max(axis=1)

    fig, axes = plt.subplots(1, 2, figsize=(11, 4.8), constrained_layout=True)
    rng = np.random.default_rng(0)

    # ── Violin ────────────────────────────────────────────────────────────────
    ax = axes[0]
    groups  = [uncertainties[correct], uncertainties[~correct]]
    labels  = ["Correct", "Misclassified"]
    colors  = [_CB4[0], _RED]
    pos     = [1, 2]

    parts = ax.violinplot(groups, positions=pos,
                          showmedians=True, showextrema=True, widths=0.55)
    for i, body in enumerate(parts["bodies"]):
        body.set_facecolor(colors[i])
        body.set_alpha(0.65)
        body.set_edgecolor("none")

    for key in ("cmedians", "cbars", "cmins", "cmaxes"):
        parts[key].set_color("black")
        parts[key].set_linewidth(1.2)

    # Strip-plot overlay
    for i, (grp, p) in enumerate(zip(groups, pos)):
        jitter = rng.uniform(-0.09, 0.09, size=len(grp))
        ax.scatter(p + jitter, grp,
                   color=colors[i], alpha=0.22, s=7, zorder=3, linewidths=0)

    ax.set_xticks(pos)
    ax.set_xticklabels(labels)
    ax.set_ylabel("Predictive Entropy  H[y|x]  (bits)")
    ax.set_title("Uncertainty by Prediction Outcome")
    _despine(ax)

    # ── Scatter ───────────────────────────────────────────────────────────────
    ax = axes[1]
    ax.scatter(max_conf[correct],  uncertainties[correct],
               color=_CB4[0], alpha=0.40, s=14, linewidths=0, label="Correct")
    ax.scatter(max_conf[~correct], uncertainties[~correct],
               color=_RED,    alpha=0.65, s=14, linewidths=0, marker="X",
               label="Misclassified")
    ax.set_xlabel("Max Predicted Probability  (Confidence)")
    ax.set_ylabel("Predictive Entropy  (bits)")
    ax.set_title("Confidence vs. Uncertainty")
    ax.legend()
    _despine(ax)

    save_figure(fig, "fig4_uncertainty_reliability")
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# Figure 5 — Model Calibration (Reliability Diagram)
# ══════════════════════════════════════════════════════════════════════════════

def plot_calibration_curve_fig(
    y_true: np.ndarray,
    y_probs: np.ndarray,
    n_bins: int = 10,
) -> plt.Figure:
    """
    Reliability diagram: predicted confidence vs. empirical accuracy.
    The dashed diagonal is the ideal perfectly-calibrated reference.
    Gap shading indicates over/under-confidence regions per class.

    Parameters
    ----------
    y_true  : (N,) true class indices
    y_probs : (N, 4) predicted probabilities
    n_bins  : number of equal-width bins for calibration_curve
    """
    y_bin = label_binarize(y_true, classes=list(range(N_CLASSES)))

    fig, ax = plt.subplots(figsize=(5.5, 5.5))
    ax.plot([0, 1], [0, 1], "k--", linewidth=1.2, label="Perfect calibration")

    for i, name in enumerate(CLASS_NAMES):
        frac_pos, mean_pred = calibration_curve(
            y_bin[:, i], y_probs[:, i],
            n_bins=n_bins, strategy="uniform",
        )
        ax.plot(mean_pred, frac_pos, "o-",
                color=_CB4[i], linewidth=1.6, markersize=5, label=name)
        ax.fill_between(mean_pred, mean_pred, frac_pos,
                        alpha=0.08, color=_CB4[i])

    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_xlabel("Mean Predicted Probability")
    ax.set_ylabel("Fraction of Positives  (Empirical Frequency)")
    ax.set_title("Reliability Diagram — Model Calibration")
    ax.legend(loc="upper left")
    _despine(ax)

    fig.tight_layout()
    save_figure(fig, "fig5_calibration_curve")
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# Figure 6 — Accuracy–Rejection Curve (Clinical Deferral)
# ══════════════════════════════════════════════════════════════════════════════

def plot_accuracy_rejection_curve(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    uncertainties: np.ndarray,
    max_rejection: float = 0.50,
    n_steps: int = 100,
) -> plt.Figure:
    """
    Shows how model accuracy on retained samples rises as the top-X% most
    uncertain predictions are deferred to a human radiologist.

    Parameters
    ----------
    y_true         : (N,) true class indices
    y_pred         : (N,) predicted class indices
    uncertainties  : (N,) predictive entropy values
    max_rejection  : maximum fraction to defer  (default 0.50 → 50%)
    n_steps        : resolution of the X-axis grid
    """
    n              = len(y_true)
    baseline_acc   = (y_true == y_pred).mean()
    fracs          = np.linspace(0, max_rejection, n_steps)
    accs           = np.full(n_steps, np.nan)
    # Indices sorted highest → lowest uncertainty (most uncertain first)
    sorted_by_unc  = np.argsort(uncertainties)[::-1]

    for k, frac in enumerate(fracs):
        n_reject   = int(frac * n)
        keep_mask  = np.ones(n, dtype=bool)
        if n_reject > 0:
            keep_mask[sorted_by_unc[:n_reject]] = False
        if keep_mask.sum() > 0:
            accs[k] = (y_true[keep_mask] == y_pred[keep_mask]).mean()

    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    ax.plot(fracs * 100, accs * 100,
            color=_CB4[0], linewidth=2.2, label="MC-Dropout model")
    ax.axhline(baseline_acc * 100, color="gray", linestyle="--", linewidth=1.2,
               label=f"No-rejection baseline  ({baseline_acc*100:.1f}%)")
    ax.fill_between(fracs * 100,
                    baseline_acc * 100,
                    np.where(np.isnan(accs), baseline_acc, accs) * 100,
                    where=(accs >= baseline_acc),
                    alpha=0.14, color=_CB4[0], label="Accuracy gain")

    ax.set_xlim(0, max_rejection * 100)
    ax.set_xlabel("Fraction of Samples Deferred to Radiologist  (%)")
    ax.set_ylabel("Accuracy on Retained Samples  (%)")
    ax.set_title("Accuracy–Rejection Curve  (Clinical Deferral)")
    ax.legend()
    _despine(ax)

    fig.tight_layout()
    save_figure(fig, "fig6_accuracy_rejection_curve")
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# Figure 7 — Latent Space Projection (t-SNE)
# ══════════════════════════════════════════════════════════════════════════════

def plot_tsne(
    embeddings: np.ndarray,
    y_true: np.ndarray,
    uncertainties: np.ndarray,
    perplexity: float = 40,
    n_iter: int = 1_000,
) -> plt.Figure:
    """
    Reduces 768-D ViT embeddings to 2-D via t-SNE and plots two views:
      Left : colored by true class label.
      Right: colored by predictive entropy (continuous plasma colormap).

    Parameters
    ----------
    embeddings    : (N, 768) ViT CLS-token representations
    y_true        : (N,) true class indices
    uncertainties : (N,) predictive entropy values
    perplexity    : t-SNE perplexity  (recommended: 30–50)
    n_iter        : t-SNE iterations  (≥ 1000 for stability)
    """
    print(f"    Running t-SNE  (n={len(embeddings)}, perplexity={perplexity}) …")
    tsne   = TSNE(n_components=2, perplexity=perplexity, n_iter=n_iter,
                  init="pca", learning_rate="auto", random_state=42)
    emb2d  = tsne.fit_transform(embeddings)
    print(f"    t-SNE done.  KL divergence = {tsne.kl_divergence_:.4f}")

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5), constrained_layout=True)
    dot_kw = dict(s=10, alpha=0.75, linewidths=0)

    # ── Left: True Class ──────────────────────────────────────────────────────
    ax = axes[0]
    for i, name in enumerate(CLASS_NAMES):
        mask = y_true == i
        ax.scatter(emb2d[mask, 0], emb2d[mask, 1],
                   color=_CB4[i], label=name, **dot_kw)
    ax.set_xlabel("t-SNE Dim 1")
    ax.set_ylabel("t-SNE Dim 2")
    ax.set_title("Latent Space — True Class")
    ax.legend(markerscale=2.2, fontsize=9.5)
    ax.set_xticks([]); ax.set_yticks([])
    _despine(ax)

    # ── Right: Predictive Entropy ─────────────────────────────────────────────
    ax = axes[1]
    sc = ax.scatter(emb2d[:, 0], emb2d[:, 1],
                    c=uncertainties, cmap="plasma", **dot_kw)
    cbar = fig.colorbar(sc, ax=ax, fraction=0.046, pad=0.04, shrink=0.92)
    cbar.set_label("Predictive Entropy  H[y|x]  (bits)", fontsize=10)
    cbar.ax.tick_params(labelsize=8)
    ax.set_xlabel("t-SNE Dim 1")
    ax.set_ylabel("t-SNE Dim 2")
    ax.set_title("Latent Space — Predictive Uncertainty")
    ax.set_xticks([]); ax.set_yticks([])
    _despine(ax)

    save_figure(fig, "fig7_tsne_latent_space")
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# Synthetic Data Generator  (for standalone testing)
# ══════════════════════════════════════════════════════════════════════════════

def generate_synthetic_data(
    n_samples: int = 800,
    n_epochs:  int = 60,
    seed:      int = 42,
) -> dict:
    """
    Produces realistic-looking synthetic arrays matching all function signatures.

    Returns a dict with keys:
        history, best_epoch, y_true, y_pred, y_probs, uncertainties, embeddings
    """
    rng = np.random.default_rng(seed)
    t   = np.linspace(0, 1, n_epochs)

    # ── Training curves ───────────────────────────────────────────────────────
    train_loss = 1.45 * np.exp(-3.8 * t) + 0.05 + rng.normal(0, 0.012, n_epochs)
    val_loss   = 1.55 * np.exp(-3.2 * t) + 0.13 + rng.normal(0, 0.018, n_epochs)
    val_loss[40:] += np.linspace(0, 0.09, n_epochs - 40)   # mild overfitting
    train_acc  = np.clip(1 - 0.90 * np.exp(-4.2 * t) + rng.normal(0, 0.009, n_epochs), 0, 1)
    val_acc    = np.clip(1 - 0.88 * np.exp(-3.6 * t) + rng.normal(0, 0.011, n_epochs), 0, 1)
    best_epoch = int(np.argmin(val_loss)) + 1

    history = dict(train_loss=train_loss.tolist(), val_loss=val_loss.tolist(),
                   train_acc=train_acc.tolist(),   val_acc=val_acc.tolist())

    # ── Class-balanced ground truth ───────────────────────────────────────────
    y_true = np.repeat(np.arange(N_CLASSES), n_samples // N_CLASSES)
    y_true = np.concatenate([y_true, rng.integers(0, N_CLASSES, n_samples % N_CLASSES)])
    rng.shuffle(y_true)

    # ── Softmax probabilities  (~91% accuracy) ────────────────────────────────
    y_probs = rng.dirichlet(alpha=[0.4] * N_CLASSES, size=n_samples)
    boost   = rng.uniform(2.0, 5.0, size=n_samples)
    for i in range(n_samples):
        y_probs[i, y_true[i]] += boost[i]
    y_probs /= y_probs.sum(axis=1, keepdims=True)
    y_pred   = y_probs.argmax(axis=1)

    # ── Predictive entropy ────────────────────────────────────────────────────
    eps           = 1e-9
    uncertainties = -(y_probs * np.log(y_probs + eps)).sum(axis=1)

    # ── Simulated 768-D ViT embeddings ────────────────────────────────────────
    embeddings = np.zeros((n_samples, 768))
    for cls in range(N_CLASSES):
        idx   = np.where(y_true == cls)[0]
        mean  = rng.normal(cls * 6, 1.5, size=768)
        embeddings[idx] = rng.normal(mean, 1.8, size=(len(idx), 768))

    return dict(
        history=history, best_epoch=best_epoch,
        y_true=y_true, y_pred=y_pred, y_probs=y_probs,
        uncertainties=uncertainties, embeddings=embeddings,
    )


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    set_global_style()

    banner = "Brain Tumor ViT + MC Dropout — Publication Figure Suite"
    print("=" * len(banner))
    print(banner)
    print("=" * len(banner))

    print("\n[*] Generating synthetic data …")
    data = generate_synthetic_data(n_samples=800, n_epochs=60)

    h   = data["history"]
    be  = data["best_epoch"]
    yt  = data["y_true"]
    yp  = data["y_pred"]
    ypr = data["y_probs"]
    unc = data["uncertainties"]
    emb = data["embeddings"]

    acc = (yt == yp).mean() * 100
    print(f"    Samples: {len(yt)}  |  Classes: {N_CLASSES}  |  "
          f"Best epoch: {be}  |  Test accuracy: {acc:.1f}%")

    steps = [
        ("[1/7] Training dynamics …",           lambda: plot_training_dynamics(h, best_epoch=be)),
        ("[2/7] Confusion matrix …",            lambda: plot_confusion_matrix(yt, yp)),
        ("[3/7] ROC & PR curves …",             lambda: plot_roc_pr_curves(yt, ypr)),
        ("[4/7] Uncertainty reliability …",     lambda: plot_uncertainty_reliability(yt, yp, ypr, unc)),
        ("[5/7] Model calibration …",           lambda: plot_calibration_curve_fig(yt, ypr)),
        ("[6/7] Accuracy–rejection curve …",    lambda: plot_accuracy_rejection_curve(yt, yp, unc)),
        ("[7/7] t-SNE latent space …",          lambda: plot_tsne(emb, yt, unc)),
    ]

    figs = []
    for label, fn in steps:
        print(f"\n{label}")
        figs.append(fn())

    print(f"\n{'=' * len(banner)}")
    print(f" All 7 figures saved to ./{OUTPUT_DIR}/  (PDF + PNG, 300 DPI)")
    print(f"{'=' * len(banner)}\n")

    plt.show()


if __name__ == "__main__":
    main()
